name: vocal-separator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.23.5
  - numba=0.56.4
  - scipy=1.9.3
  - librosa=0.9.2
  - pip:
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - python-multipart>=0.0.5
    - aiofiles>=0.7.0
    - pretty_midi>=0.2.9
    - pydantic>=1.8.0
    - websockets>=10.0
    - python-dotenv>=0.19.0
    - midiutil>=1.2.1
    - soundfile>=0.12.0 